name: GFD Process Feature

env:
  GITEA_INTERNAL_URL: http://192.168.8.109:3000

on:
  workflow_dispatch:
    inputs:
      slug:
        description: 'Feature slug to process'
        required: true
        type: string
      type:
        description: 'Operation type'
        required: true
        type: choice
        options:
          - research
          - plan

jobs:
  process:
    runs-on: claude
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITEA_TOKEN }}

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Setup gfd-tools
        run: |
          chmod +x get-features-done/bin/gfd-tools
          mkdir -p /home/conroy/.claude/agents
          cp agents/*.md /home/conroy/.claude/agents/

      - name: Install tea CLI
        run: |
          curl -sL https://dl.gitea.com/tea/0.10.1/tea-0.10.1-linux-amd64 -o /usr/local/bin/tea
          chmod +x /usr/local/bin/tea

      - name: Setup tea auth
        run: |
          tea login add \
            --url "$GITEA_INTERNAL_URL" \
            --token "${{ secrets.GITEA_TOKEN }}" \
            --name ci

      - name: Configure git
        run: |
          git config user.name "GFD CI"
          git config user.email "ci@gitea.local"

      - name: Create feature branch
        run: git checkout -B "ci/${{ inputs.slug }}"

      - name: Run GFD auto operation
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          set -e
          if [ "${{ inputs.type }}" = "research" ]; then
            ./get-features-done/bin/gfd-tools auto-research "${{ inputs.slug }}"
          else
            ./get-features-done/bin/gfd-tools auto-plan "${{ inputs.slug }}"
          fi

      - name: Commit results
        run: |
          git add -A
          git diff --cached --quiet || git commit -m "ci(${{ inputs.slug }}): auto-${{ inputs.type }} results"

      - name: Push branch
        run: git push origin "ci/${{ inputs.slug }}"

      - name: Create PR
        run: |
          tea pulls create \
            --title "ci(${{ inputs.slug }}): auto-${{ inputs.type }}" \
            --base main \
            --head "ci/${{ inputs.slug }}" \
            --description "Automated ${{ inputs.type }} run for feature: ${{ inputs.slug }}"
