name: GFD Process Feature

env:
  GITEA_INTERNAL_URL: http://192.168.8.109:3000
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

on:
  workflow_dispatch:
    inputs:
      slug:
        description: 'Feature slug to process'
        required: true
        type: string
      type:
        description: 'Operation type'
        required: true
        type: choice
        options:
          - research
          - plan

concurrency:
  group: gfd-process-${{ inputs.slug }}
  cancel-in-progress: false

jobs:
  process:
    runs-on: claude
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITEA_TOKEN }}

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Setup gfd-tools
        run: |
          chmod +x get-features-done/bin/gfd-tools
          mkdir -p "$HOME/.claude/agents"
          cp agents/*.md "$HOME/.claude/agents/"

      - name: Configure git
        run: |
          git config user.name "GFD CI"
          git config user.email "ci@gitea.local"

      - name: Create feature branch
        run: git checkout -B "ci/${{ inputs.slug }}"

      - name: Run GFD auto operation
        env:
          CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          if [ "${{ inputs.type }}" = "research" ]; then
            ./get-features-done/bin/gfd-tools auto-research "${{ inputs.slug }}" 2>&1 | tee /tmp/gfd-output.log
          else
            ./get-features-done/bin/gfd-tools auto-plan "${{ inputs.slug }}" 2>&1 | tee /tmp/gfd-output.log
          fi

      - name: Commit results
        run: |
          git add -A
          git diff --cached --quiet || git commit -m "ci(${{ inputs.slug }}): auto-${{ inputs.type }} results"

      - name: Push branch
        run: git push origin "ci/${{ inputs.slug }}"

      - name: Create PR
        run: |
          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Authorization: token ${{ secrets.CREATE_PR_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "title": "ci(${{ inputs.slug }}): auto-${{ inputs.type }}",
              "head": "ci/${{ inputs.slug }}",
              "base": "main",
              "body": "Automated ${{ inputs.type }} run for feature: ${{ inputs.slug }}"
            }' \
            "$GITEA_INTERNAL_URL/api/v1/repos/${{ github.repository }}/pulls")
          HTTP_CODE=$(echo "$RESPONSE" | tail -1)
          BODY=$(echo "$RESPONSE" | sed '$d')
          echo "HTTP $HTTP_CODE"
          echo "$BODY"
          [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 300 ]

      - name: Debug output
        if: always()
        run: |
          echo "========== GFD Output =========="
          cat /tmp/gfd-output.log 2>/dev/null || echo "No output captured"
          echo "========== AUTO-RUN.md =========="
          cat "docs/features/${{ inputs.slug }}/AUTO-RUN.md" 2>/dev/null || echo "No AUTO-RUN.md found"
          echo "========== Git Status =========="
          git status
          echo "========== Recent Commits =========="
          git log --oneline -5
