name: GFD Nightly

env:
  GITEA_INTERNAL_URL: http://192.168.8.109:3000
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

on:
  schedule:
    - cron: '0 3 * * *'   # 3 AM UTC daily
  workflow_dispatch:

concurrency:
  group: gfd-nightly
  cancel-in-progress: true

jobs:
  orchestrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITEA_TOKEN }}

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Setup gfd-tools
        run: chmod +x get-features-done/bin/gfd-tools

      - name: Install tea CLI
        run: |
          curl -sL https://dl.gitea.com/tea/0.10.1/tea-0.10.1-linux-amd64 -o /usr/local/bin/tea
          chmod +x /usr/local/bin/tea

      - name: Setup tea auth
        run: |
          tea login add \
            --url "$GITEA_INTERNAL_URL" \
            --token "${{ secrets.GITEA_TOKEN }}" \
            --name ci

      - name: Discover and dispatch features
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
        run: |
          REPO="${{ github.repository }}"
          WORKFLOW="gfd-process-feature.yml"
          DISPATCHED=0
          SKIPPED=0

          dispatch() {
            local SLUG="$1"
            local TYPE="$2"

            # Skip if ci/<slug> branch already exists on remote
            if git ls-remote --exit-code origin "refs/heads/ci/$SLUG" > /dev/null 2>&1; then
              echo "SKIPPED: $SLUG — branch ci/$SLUG already exists"
              SKIPPED=$((SKIPPED + 1))
              return
            fi

            # Skip if open PR exists for ci/<slug>
            PR_EXISTS=$(tea pulls list --state open --fields head --output simple 2>/dev/null \
              | grep -c "ci/$SLUG" || true)
            if [ "${PR_EXISTS:-0}" -gt 0 ] 2>/dev/null; then
              echo "SKIPPED: $SLUG — open PR already exists"
              SKIPPED=$((SKIPPED + 1))
              return
            fi

            # Trigger sub-workflow via Gitea API
            echo "DISPATCHING: $SLUG ($TYPE)"
            HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
              -X POST "$GITEA_INTERNAL_URL/api/v1/repos/$REPO/actions/workflows/$WORKFLOW/dispatches" \
              -H "Authorization: token $GITEA_TOKEN" \
              -H "Content-Type: application/json" \
              -d "{\"ref\":\"main\",\"inputs\":{\"slug\":\"$SLUG\",\"type\":\"$TYPE\"}}")

            if [ "$HTTP_CODE" = "204" ] || [ "$HTTP_CODE" = "200" ]; then
              echo "  -> Dispatched successfully"
              DISPATCHED=$((DISPATCHED + 1))
            else
              echo "  -> Failed to dispatch (HTTP $HTTP_CODE)"
            fi
          }

          # Auto-detect: discussed → research, researched → plan
          DISCUSSED=$(./get-features-done/bin/gfd-tools list-features --status discussed \
            | grep "^feature_slug=" | cut -d= -f2 || true)
          RESEARCHED=$(./get-features-done/bin/gfd-tools list-features --status researched \
            | grep "^feature_slug=" | cut -d= -f2 || true)

          for s in $DISCUSSED; do dispatch "$s" "research"; done
          for s in $RESEARCHED; do dispatch "$s" "plan"; done

          echo ""
          echo "==============================="
          echo "Dispatched: $DISPATCHED | Skipped: $SKIPPED"
          echo "==============================="
