name: Test PR Creation

env:
  GITEA_INTERNAL_URL: http://192.168.8.109:3000

on:
  workflow_dispatch:

jobs:
  test-pr:
    runs-on: claude
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITEA_TOKEN }}

      - name: Diagnose repo API
        run: |
          TOKEN="${{ secrets.GITEA_TOKEN }}"
          echo "=== Authenticated user ==="
          curl -s -H "Authorization: token $TOKEN" "$GITEA_INTERNAL_URL/api/v1/user" | head -c 300
          echo ""
          echo ""
          echo "=== Repo info ==="
          curl -s -H "Authorization: token $TOKEN" "$GITEA_INTERNAL_URL/api/v1/repos/conroy-gitea/Get-Features-Done" | grep -E '"full_name"|"has_pull_requests"|"internal"|"private"|"permissions"'
          echo ""
          echo "=== Repo units ==="
          curl -s -H "Authorization: token $TOKEN" "$GITEA_INTERNAL_URL/api/v1/repos/conroy-gitea/Get-Features-Done" | python3 -c "import sys,json; d=json.load(sys.stdin); print('has_pull_requests:', d.get('has_pull_requests')); print('repo_type:', d.get('repo_transfer',{}))" 2>/dev/null || echo "python3 parse failed"
          echo ""
          echo "=== List existing PRs ==="
          curl -s -w "\nHTTP: %{http_code}" -H "Authorization: token $TOKEN" "$GITEA_INTERNAL_URL/api/v1/repos/conroy-gitea/Get-Features-Done/pulls?state=all&limit=3"
          echo ""
          echo ""
          echo "=== Try POST ==="
          curl -s -w "\nHTTP: %{http_code}" -X POST \
            -H "Authorization: token $TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"title":"test","head":"ci/cleanup-progress","base":"main","body":"test"}' \
            "$GITEA_INTERNAL_URL/api/v1/repos/conroy-gitea/Get-Features-Done/pulls"
          echo ""
